version: '3'
services:
  backend:
    container_name: wishlist_api_backend
    build: .
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI="$SQLALCHEMY_DATABASE_URI"
      - SECRET_KEY="$SECRET_KEY"
      - GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"
      - GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET"
